-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Authentications"
(
    id integer NOT NULL,
    "playerId" integer NOT NULL,
    email character varying(50) COLLATE pg_catalog."default",
    "passwordHash" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Authentications_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."ChatMessages"
(
    id integer NOT NULL,
    "chatId" integer NOT NULL,
    content character varying(250) COLLATE pg_catalog."default",
    "playerId" integer NOT NULL,
    "sendDate" date NOT NULL,
    CONSTRAINT "ChatMessages_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Chats"
(
    id integer NOT NULL,
    "gameSessionId" integer NOT NULL,
    CONSTRAINT "Chats_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."DirectMessages"
(
    id integer NOT NULL,
    "receiverPlayerId" integer NOT NULL,
    "senderPlayerId" integer NOT NULL,
    content character varying(250) COLLATE pg_catalog."default",
    "sendDate" date NOT NULL,
    "hasRead" boolean NOT NULL,
    CONSTRAINT "DirectMessages_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Friends"
(
    "playerId" integer NOT NULL,
    "friendId" integer NOT NULL,
    CONSTRAINT "Friends_pkey" PRIMARY KEY ("playerId")
);

CREATE TABLE IF NOT EXISTS public."GameSessions"
(
    id integer NOT NULL,
    "startDate" date NOT NULL,
    "endDate" date NOT NULL,
    CONSTRAINT "GameSessions_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Players"
(
    id integer NOT NULL,
    "firstName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "lastName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "authenticationId" integer NOT NULL,
    "regionId" integer NOT NULL,
    CONSTRAINT "Players_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."ReactionTypes"
(
    id integer NOT NULL,
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "ReactionTypes_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Reactions"
(
    id integer NOT NULL,
    "reactionTypeId" integer NOT NULL,
    "targetPlayerId" integer NOT NULL,
    "gameSessionId" integer NOT NULL,
    "reactedPlayerId" integer NOT NULL,
    CONSTRAINT "Reactions_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Regions"
(
    id integer NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "timeZone" date,
    CONSTRAINT "Regions_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."ChatMessages"
    ADD CONSTRAINT "FK_ChatMessages_Chats" FOREIGN KEY ("chatId")
    REFERENCES public."Chats" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."ChatMessages"
    ADD CONSTRAINT "FK_ChatMessages_Players" FOREIGN KEY ("playerId")
    REFERENCES public."Players" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Chats"
    ADD CONSTRAINT "FK_Chats_GameSessions" FOREIGN KEY ("gameSessionId")
    REFERENCES public."GameSessions" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."DirectMessages"
    ADD CONSTRAINT "FK_DirectMessages_Player_ReceiverPlayer" FOREIGN KEY ("receiverPlayerId")
    REFERENCES public."Players" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."DirectMessages"
    ADD CONSTRAINT "FK_DirectMessages_Player_SenderPlayer" FOREIGN KEY ("senderPlayerId")
    REFERENCES public."Players" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Friends"
    ADD CONSTRAINT "FK_Friends_Players" FOREIGN KEY ("playerId")
    REFERENCES public."Players" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "Friends_pkey"
    ON public."Friends"("playerId");


ALTER TABLE IF EXISTS public."Players"
    ADD CONSTRAINT "FK_Players_Authentications" FOREIGN KEY ("authenticationId")
    REFERENCES public."Authentications" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Players"
    ADD CONSTRAINT "FK_Players_Regions" FOREIGN KEY ("regionId")
    REFERENCES public."Regions" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reactions"
    ADD CONSTRAINT "FK_Reactions_GameSessions" FOREIGN KEY ("gameSessionId")
    REFERENCES public."GameSessions" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Reactions"
    ADD CONSTRAINT "FK_Reactions_Players_ReactedPlayer" FOREIGN KEY ("reactedPlayerId")
    REFERENCES public."Players" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reactions"
    ADD CONSTRAINT "FK_Reactions_Players_TargetPlayer" FOREIGN KEY ("targetPlayerId")
    REFERENCES public."Players" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reactions"
    ADD CONSTRAINT "FK_Reactions_ReactionTypes" FOREIGN KEY ("reactionTypeId")
    REFERENCES public."ReactionTypes" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;